const palette = {
  primaryPurple: "#6B558E",
  primaryPurpleHover: "#463660",
  warningRed: "#D03B18",
  warningRedHover: "#94675D",
  successGreen: "#437906",
  black: "#000000",
  white: "#FFFFFF",
  darkestgrey: "#323232",
  darkGrey: "#6D6D6D",
  mediumgrey: "#A6A6A6",
  lightGrey: "#E8E8E8",
  ultraLightGrey: "#F5F5F5",
  bug: "#7E9F58",
  normal: "#A8A878",
  grass: "#8EA68D",
  dark: "#57493F",
  fighting: "#D26E31",
  fire: "#FA9F61",
  electric: "#F6DA76",
  dragon: "#A0494E",
  psychic: "#E9708F",
  ghost: "#887A9F",
  poison: "#CDA0CA",
  flying: "#C1B7DE",
  steel: "#C4C4CC",
  fairy: "#FFC5D4",
  rock: "#A28C21",
  ground: "#D6C67A",
  ice: "#33D4D4",
  water: "#89F3FA",

  // === DARK THEME ===
  dark_primaryPurple: "#A387D1",
  dark_primaryPurpleHover: "#BCA4E6",
  dark_warningRed: "#FF6B6B",
  dark_warningRedHover: "#FFA1A1",
  dark_successGreen: "#71C055",
  dark_black: "#FFFFFF",
  dark_white: "#121212",
  dark_darkestgrey: "#E0E0E0",
  dark_darkGrey: "#A6A6A6",
  dark_mediumgrey: "#6D6D6D",
  dark_lightGrey: "#323232",
  dark_ultraLightGrey: "#1E1E1E",
  dark_bug: "#A8B820",
  dark_normal: "#A8A878",
  dark_grass: "#78C850",
  dark_dark: "#705848",
  dark_fighting: "#C03028",
  dark_fire: "#F08030",
  dark_electric: "#F8D030",
  dark_dragon: "#7038F8",
  dark_psychic: "#F85888",
  dark_ghost: "#705898",
  dark_poison: "#A040A0",
  dark_flying: "#A890F0",
  dark_steel: "#B8B8D0",
  dark_fairy: "#EE99AC",
  dark_rock: "#B8A038",
  dark_ground: "#E0C068",
  dark_ice: "#98D8D8",
  dark_water: "#6890F0",
};

export const lightColors = {
  // Core Colors
  primaryPurple: palette.primaryPurple,
  primaryPurpleHover: palette.primaryPurpleHover,
  warningRed: palette.warningRed,
  warningRedHover: palette.warningRedHover,
  successGreen: palette.successGreen,
  black: palette.black,
  white: palette.white,

  // Grayscale
  darkestgrey: palette.darkestgrey,
  darkGrey: palette.darkGrey,
  mediumgrey: palette.mediumgrey,
  lightGrey: palette.lightGrey,
  ultraLightGrey: palette.ultraLightGrey,

  // Pokémon Types
  bug: palette.bug,
  normal: palette.normal,
  grass: palette.grass,
  dark: palette.dark,
  fighting: palette.fighting,
  fire: palette.fire,
  electric: palette.electric,
  dragon: palette.dragon,
  psychic: palette.psychic,
  ghost: palette.ghost,
  poison: palette.poison,
  flying: palette.flying,
  steel: palette.steel,
  fairy: palette.fairy,
  rock: palette.rock,
  ground: palette.ground,
  ice: palette.ice,
  water: palette.water,
};

export const darkColors: typeof lightColors = {
  // Core Colors
  primaryPurple: palette.dark_primaryPurple,
  primaryPurpleHover: palette.dark_primaryPurpleHover,
  warningRed: palette.dark_warningRed,
  warningRedHover: palette.dark_warningRedHover,
  successGreen: palette.dark_successGreen,
  black: palette.dark_black,
  white: palette.dark_white,

  // Grayscale
  darkestgrey: palette.dark_darkestgrey,
  darkGrey: palette.dark_darkGrey,
  mediumgrey: palette.dark_mediumgrey,
  lightGrey: palette.dark_lightGrey,
  ultraLightGrey: palette.dark_ultraLightGrey,

  // Pokémon Types
  bug: palette.dark_bug,
  normal: palette.dark_normal,
  grass: palette.dark_grass,
  dark: palette.dark_dark,
  fighting: palette.dark_fighting,
  fire: palette.dark_fire,
  electric: palette.dark_electric,
  dragon: palette.dark_dragon,
  psychic: palette.dark_psychic,
  ghost: palette.dark_ghost,
  poison: palette.dark_poison,
  flying: palette.dark_flying,
  steel: palette.dark_steel,
  fairy: palette.dark_fairy,
  rock: palette.dark_rock,
  ground: palette.dark_ground,
  ice: palette.dark_ice,
  water: palette.dark_water,
};
